# This is a basic workflow to help you get started with Actions

name: Copy Compiled Site to threathunterz.com

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          # The Hugo version to download (if necessary) and use. Example: 0.58.2
          # Download (if necessary) and use Hugo extended version. Example: true
          extended: true
  
      - name: Build Hugo Site
        run: hugo --minify

      # Runs a single command using the runners shell
      - name: List contents of Public folder
        run: ls -lahr ./public

      - name: Pushes changes to threathunterz.com
        uses: darkquasar/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'resources'
          target-directory: 'static'
          destination-github-username: 'darkquasar'
          destination-repository-name: 'test-repo'
          user-email: darkquasar7@gmail.com
