name: Publish Site

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          # The Hugo version to download (if necessary) and use. Example: 0.58.2
          # Download (if necessary) and use Hugo extended version. Example: true
          extended: true
  
      - name: Build
        run: hugo --minify

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls -lahr
